#!/bin/bash

L=0
while [[ true ]]
do
	L=`expr $L + 1`

	if [[ $(uname -n) == "leaf1" ]]
	then
		go run web.go -p 3000 -a 10.11.13.7 -u /home/bgolden/igendecDB 2>&1 | tee log.$L
	else
		go run web.go -p 3000 -a localhost -u /home/bgolden/tmp/igendecDB 2>&1 | tee log.$L
	fi
	
done
