#!/bin/bash

FILE=minert.csv

head -1 $FILE | sed 's/ /_/g' >h

SKIP=1
if [[ $SKIP != 1 ]]
then
awk -F , 'BEGIN{print "["}
{
	for(i=1; i<=NF; i++ ){

		if( $i == "%_Rank" )
			$i = pval "_" $i
		print "\t{"
		print "\t\tname:" $i
		print "\t\theader:" $i
		print "\t\tcomment:" $i 
		print "\t\tselect:false"
		print "\t}"

		pval = $i
	}
}
END{print "]"}' h >comp_fn_pairs.hjson
fi

awk 'NR>1{print $0}' $FILE >>h
sed 's/+//g' h >"tmp"$FILE

awk -F , '{
	if( NR == 1 )
		print $0
	else {
		for( i=1; i<=NF; i++ ) {
			if( $i == "" )
				$i = 0
		}

		for( i=1; i<NF; i++ )
			printf("%s,", $i)
		printf "%s\n", $NF
	}
}' "tmp"$FILE >"upload"$FILE
